version: '3'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: nodemon /app/index.js
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - "1234:1234"